language: python
python:
  - "3.6"    # current default Python on Travis CI
  - "3.7"
  - "3.8"
jobs:
  allow_failures:
    - python: "3.8-dev"  # 3.8 development branch
    - python: "nightly"  # nightly build
# command to install dependencies
before_install:
  - python --version
install:
  - pip install .
  - pip install codecov  # only required for `after_success`
  - add-apt-repository ppa:mscore-ubuntu/mscore3-stable -y
  - apt-get update
  - apt-get install musescore3
  # - curl -L https://cdn.jsdelivr.net/musescore/v3.6.2/MuseScore-3.6.2.548021370-x86_64.AppImage --output musescore-x86_64.AppImage
  # - chmod u+x musescore-x86_64.AppImage
  # - ./musescore-x86_64.AppImage
# command to run tests - the required packages, pytest-runner, pytest, and pytest-cov
# are installed as configured in setup.cfg under setup_requires and tests_require
script:
  - python setup.py test
after_success:
  - codecov
